<?xml version="1.0" encoding="utf-8"?><Database Name="testingbd" Class="LinqTdsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\testingbd.mdf;Integrated Security=True" SettingsObjectName="SQL_App1.Properties.Settings" SettingsPropertyName="testingbdConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.chats" Member="chats">
    <Type Name="chats">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="creator" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="member" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="messagesCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.messages" Member="messages">
    <Type Name="messages">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="sender" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="chatId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="message" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.accounts" Member="accounts">
    <Type Name="accounts">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>